import { db } from '@/db';
import { vehicles } from '@/db/schema';

async function main() {
    const now = Date.now();
    const oneDay = 24 * 60 * 60 * 1000;
    
    const sampleVehicles = [
        {
            vin: 'MA3ERC66S00450671',
            make: 'Maruti Suzuki',
            model: 'Swift',
            year: 2024,
            category: 'Hatchback',
            color: 'Pearl White',
            price: 850000,
            stock: 12,
            reorderPoint: 5,
            status: 'in_stock',
            createdAt: now - (15 * oneDay),
            updatedAt: now - (2 * oneDay),
        },
        {
            vin: 'MA3EWE81S00389654',
            make: 'Maruti Suzuki',
            model: 'Baleno',
            year: 2024,
            category: 'Hatchback',
            color: 'Nexa Blue',
            price: 950000,
            stock: 10,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (20 * oneDay),
            updatedAt: now - (3 * oneDay),
        },
        {
            vin: 'MAT650031K1D08234',
            make: 'Tata',
            model: 'Nexon',
            year: 2024,
            category: 'SUV',
            color: 'Foliage Green',
            price: 1200000,
            stock: 8,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (10 * oneDay),
            updatedAt: now - (1 * oneDay),
        },
        {
            vin: 'MAT630046K1C12567',
            make: 'Tata',
            model: 'Nexon EV',
            year: 2024,
            category: 'EV',
            color: 'Intense Red',
            price: 1850000,
            stock: 6,
            reorderPoint: 3,
            status: 'in_stock',
            createdAt: now - (12 * oneDay),
            updatedAt: now - (1 * oneDay),
        },
        {
            vin: 'MA1TA2GM5K1234567',
            make: 'Mahindra',
            model: 'XUV700',
            year: 2024,
            category: 'SUV',
            color: 'Dazzling Silver',
            price: 2500000,
            stock: 5,
            reorderPoint: 3,
            status: 'in_stock',
            createdAt: now - (18 * oneDay),
            updatedAt: now - (2 * oneDay),
        },
        {
            vin: 'MA1TU8CL8K1098765',
            make: 'Mahindra',
            model: 'Thar',
            year: 2024,
            category: 'SUV',
            color: 'Everest White',
            price: 1650000,
            stock: 7,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (22 * oneDay),
            updatedAt: now - (4 * oneDay),
        },
        {
            vin: 'MALH0811DJK234890',
            make: 'Hyundai',
            model: 'Creta',
            year: 2024,
            category: 'SUV',
            color: 'Titan Grey',
            price: 1800000,
            stock: 9,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (14 * oneDay),
            updatedAt: now - (2 * oneDay),
        },
        {
            vin: 'MALH8911DJK567234',
            make: 'Hyundai',
            model: 'Venue',
            year: 2024,
            category: 'SUV',
            color: 'Polar White',
            price: 1150000,
            stock: 11,
            reorderPoint: 5,
            status: 'in_stock',
            createdAt: now - (16 * oneDay),
            updatedAt: now - (2 * oneDay),
        },
        {
            vin: 'MA1KC2GMHK2345678',
            make: 'Kia',
            model: 'Seltos',
            year: 2024,
            category: 'SUV',
            color: 'Aurora Black Pearl',
            price: 1900000,
            stock: 8,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (25 * oneDay),
            updatedAt: now - (5 * oneDay),
        },
        {
            vin: 'MA3FEB71S00234567',
            make: 'Maruti Suzuki',
            model: 'Brezza',
            year: 2024,
            category: 'SUV',
            color: 'Splendid Silver',
            price: 1300000,
            stock: 10,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (19 * oneDay),
            updatedAt: now - (3 * oneDay),
        },
        {
            vin: 'MALHH411DJK890123',
            make: 'Hyundai',
            model: 'i20',
            year: 2024,
            category: 'Hatchback',
            color: 'Fiery Red',
            price: 980000,
            stock: 13,
            reorderPoint: 5,
            status: 'in_stock',
            createdAt: now - (11 * oneDay),
            updatedAt: now - (1 * oneDay),
        },
        {
            vin: 'MAT621039K1D45678',
            make: 'Tata',
            model: 'Altroz',
            year: 2024,
            category: 'Hatchback',
            color: 'Downtown Red',
            price: 880000,
            stock: 9,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (17 * oneDay),
            updatedAt: now - (2 * oneDay),
        },
        {
            vin: 'MALHR811DJK345123',
            make: 'Hyundai',
            model: 'Verna',
            year: 2024,
            category: 'Sedan',
            color: 'Phantom Black',
            price: 1500000,
            stock: 7,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (21 * oneDay),
            updatedAt: now - (3 * oneDay),
        },
        {
            vin: 'MALA5311DJK789456',
            make: 'Honda',
            model: 'City',
            year: 2024,
            category: 'Sedan',
            color: 'Platinum White Pearl',
            price: 1450000,
            stock: 8,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (13 * oneDay),
            updatedAt: now - (2 * oneDay),
        },
        {
            vin: 'MA1PA2GM5K1567890',
            make: 'Mahindra',
            model: 'Scorpio-N',
            year: 2024,
            category: 'SUV',
            color: 'Midnight Black',
            price: 2200000,
            stock: 6,
            reorderPoint: 3,
            status: 'reserved',
            createdAt: now - (9 * oneDay),
            updatedAt: now - (1 * oneDay),
        },
        {
            vin: 'MAT640052K1D78901',
            make: 'Tata',
            model: 'Harrier',
            year: 2024,
            category: 'SUV',
            color: 'Oberon Black',
            price: 2100000,
            stock: 5,
            reorderPoint: 3,
            status: 'in_stock',
            createdAt: now - (24 * oneDay),
            updatedAt: now - (4 * oneDay),
        },
        {
            vin: 'MA1KC8GMHK2678901',
            make: 'Kia',
            model: 'Sonet',
            year: 2024,
            category: 'SUV',
            color: 'Glacier White Pearl',
            price: 1250000,
            stock: 10,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (15 * oneDay),
            updatedAt: now - (2 * oneDay),
        },
        {
            vin: 'MA3ERC66S00789012',
            make: 'Maruti Suzuki',
            model: 'Ertiga',
            year: 2024,
            category: 'MPV',
            color: 'Silky Silver',
            price: 1100000,
            stock: 8,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (28 * oneDay),
            updatedAt: now - (5 * oneDay),
        },
        {
            vin: 'MA1TA5GM5K1890123',
            make: 'Mahindra',
            model: 'XUV300',
            year: 2024,
            category: 'SUV',
            color: 'Red Rage',
            price: 1400000,
            stock: 7,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (26 * oneDay),
            updatedAt: now - (4 * oneDay),
        },
        {
            vin: 'MALHD711DJK901234',
            make: 'Hyundai',
            model: 'Alcazar',
            year: 2024,
            category: 'SUV',
            color: 'Stargazing Blue',
            price: 2000000,
            stock: 6,
            reorderPoint: 3,
            status: 'in_stock',
            createdAt: now - (23 * oneDay),
            updatedAt: now - (4 * oneDay),
        },
        {
            vin: 'MAT610058K1D12345',
            make: 'Tata',
            model: 'Punch',
            year: 2024,
            category: 'SUV',
            color: 'Calypso Red',
            price: 750000,
            stock: 14,
            reorderPoint: 5,
            status: 'in_stock',
            createdAt: now - (12 * oneDay),
            updatedAt: now - (1 * oneDay),
        },
        {
            vin: 'MA3ERD76S00345678',
            make: 'Maruti Suzuki',
            model: 'Dzire',
            year: 2024,
            category: 'Sedan',
            color: 'Phoenix Red',
            price: 850000,
            stock: 12,
            reorderPoint: 5,
            status: 'in_stock',
            createdAt: now - (18 * oneDay),
            updatedAt: now - (3 * oneDay),
        },
        {
            vin: 'MALA6211DJK456789',
            make: 'Honda',
            model: 'Amaze',
            year: 2024,
            category: 'Sedan',
            color: 'Radiant Red Metallic',
            price: 950000,
            stock: 11,
            reorderPoint: 5,
            status: 'in_stock',
            createdAt: now - (20 * oneDay),
            updatedAt: now - (3 * oneDay),
        },
        {
            vin: 'MA1KC5GMHK2789012',
            make: 'Kia',
            model: 'Carens',
            year: 2024,
            category: 'MPV',
            color: 'Imperial Blue',
            price: 1700000,
            stock: 7,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (16 * oneDay),
            updatedAt: now - (2 * oneDay),
        },
        {
            vin: 'MAT625063K1D23456',
            make: 'Tata',
            model: 'Safari',
            year: 2024,
            category: 'SUV',
            color: 'Tropical Mist',
            price: 2400000,
            stock: 4,
            reorderPoint: 3,
            status: 'reserved',
            createdAt: now - (8 * oneDay),
            updatedAt: now - (1 * oneDay),
        },
        {
            vin: 'MALHL611DJK567890',
            make: 'Hyundai',
            model: 'Exter',
            year: 2024,
            category: 'SUV',
            color: 'Ranger Khaki',
            price: 850000,
            stock: 13,
            reorderPoint: 5,
            status: 'in_stock',
            createdAt: now - (14 * oneDay),
            updatedAt: now - (2 * oneDay),
        },
        {
            vin: 'MA3EWA91S00678901',
            make: 'Maruti Suzuki',
            model: 'Grand Vitara',
            year: 2024,
            category: 'SUV',
            color: 'Opulent Red',
            price: 1750000,
            stock: 8,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (27 * oneDay),
            updatedAt: now - (5 * oneDay),
        },
        {
            vin: 'MA1TB2GM5K1012345',
            make: 'Mahindra',
            model: 'Bolero Neo',
            year: 2024,
            category: 'SUV',
            color: 'Rocky Beige',
            price: 1200000,
            stock: 9,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (19 * oneDay),
            updatedAt: now - (3 * oneDay),
        },
        {
            vin: 'MAT638047K1D34567',
            make: 'Tata',
            model: 'Tigor EV',
            year: 2024,
            category: 'EV',
            color: 'Daytona Grey',
            price: 1400000,
            stock: 5,
            reorderPoint: 3,
            status: 'in_stock',
            createdAt: now - (10 * oneDay),
            updatedAt: now - (1 * oneDay),
        },
        {
            vin: 'MALHA911DJK890123',
            make: 'Honda',
            model: 'Elevate',
            year: 2024,
            category: 'SUV',
            color: 'Canyon River Blue',
            price: 1650000,
            stock: 7,
            reorderPoint: 4,
            status: 'in_stock',
            createdAt: now - (21 * oneDay),
            updatedAt: now - (3 * oneDay),
        },
    ];

    await db.insert(vehicles).values(sampleVehicles);
    
    console.log('✅ Vehicles seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});